export enum CandidateStatus {
    OPEN = 'OPEN',
    WAITING_INTERVIEW = 'WAITING_INTERVIEW',
    CANCELLED_INTERVIEW = 'CANCELLED_INTERVIEW',
    PASS_INTERVIEW = 'PASS_INTERVIEW',
    FAILED_INTERVIEW = 'FAILED_INTERVIEW',
    WAITING_APPROVAL = 'WAITING_APPROVAL',
    APPROVED_OFFER = 'APPROVED_OFFER',
    REJECTED_OFFER = 'REJECTED_OFFER',
    WAITING_RESPONSE = 'WAITING_RESPONSE',
    ACCEPTED_OFFER = 'ACCEPTED_OFFER',
    DECLINED_OFFER = 'DECLINED_OFFER',
    CANCELLED_OFFER = 'CANCELLED_OFFER',
    BANNED = 'BANNED'
}